[package]
name = "examples"
version = "0.0.0"
edition.workspace = true
publish = false

[dependencies]
satex = { workspace = true }
satex-core = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[[example]]
name = "layer-cors"
path = "layer/cors/main.rs"