[package]
name = "satex-macro"
version.workspace = true
edition.workspace = true
description = "satex macro library"

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0" }
proc-macro2 = { version = "1.0" }
syn = { version = "2.0", features = ["full"] }
